In [18]:
import pandas as pd

df = pd.read_pickle('../../arxiv-metadata-oai-2019.pkl')
df

,id,submitter,authors,title,comments,journal-ref,doi,report-no,categories,license,abstract,versions,update_date,authors_parsed,group
0,0704.0297,Sung-Chul Yoon,"Sung-Chul Yoon, Philipp Podsiadlowski and Step...",Remnant evolution after a carbon-oxygen white ...,"15 pages, 15 figures, 3 tables, submitted to M...",NaN,10.1111/j.1365-2966.2007.12161.x,NaN,astro-ph,NaN,We systematically explore the evolution of t...,"[{'version': 'v1', 'created': 'Tue, 3 Apr 2007...",2019-08-19,"[['Yoon', 'Sung-Chul', ''], ['Podsiadlowski', ...",Physics
1,0704.0342,Patrice Ntumba Pungu,B. Dugmore and PP. Ntumba,Cofibrations in the Category of Frolicher Spac...,27 pages,NaN,NaN,NaN,math.AT,NaN,Cofibrations are defined in the category of ...,"[{'version': 'v1', 'created': 'Tue, 3 Apr 2007...",2019-08-19,"[['Dugmore', 'B.', ''], ['Ntumba', 'PP.', '']]",Mathematics
2,0704.0360,Zaqarashvili,T.V. Zaqarashvili and K Murawski,Torsional oscillations of longitudinally inhom...,"6 pages, 3 figures, accepted in A&A",NaN,10.1051/0004-6361:20077246,NaN,astro-ph,NaN,We explore the effect of an inhomogeneous ma...,"[{'version': 'v1', 'created': 'Tue, 3 Apr 2007...",2019-08-19,"[['Zaqarashvili', 'T. V.', ''], ['Murawski', '...",Physics
3,0704.0525,"Sezgin Ayg\""un","Sezgin Aygun, Ismail Tarhan, Husnu Baysal",On the Energy-Momentum Problem in Static Einst...,This submission has been withdrawn by arXiv ad...,"Chin.Phys.Lett.24:355-358,2007",10.1088/0256-307X/24/2/015,NaN,gr-qc,NaN,This paper has been removed by arXiv adminis...,"[{'version': 'v1', 'created': 'Wed, 4 Apr 2007...",2019-10-21,"[['Aygun', 'Sezgin', ''], ['Tarhan', 'Ismail',...",Physics
4,0704.0535,Antonio Pipino,"Antonio Pipino (1,3), Thomas H. Puzia (2,4), a...",The Formation of Globular Cluster Systems in M...,"32 pages (referee format), 9 figures, ApJ acce...","Astrophys.J.665:295-305,2007",10.1086/519546,NaN,astro-ph,NaN,The most massive elliptical galaxies show a ...,"[{'version': 'v1', 'created': 'Wed, 4 Apr 2007...",2019-08-19,"[['Pipino', 'Antonio', ''], ['Puzia', 'Thomas ...",Physics
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
170613,quant-ph/9904032,Mikhail Lukin,"V. A. Sautenkov, M. D. Lukin, C. J. Bednar, G....",Enhancement of Magneto-Optic Effects via Large...,NaN,NaN,10.1103/PhysRevA.62.023810,NaN,quant-ph,NaN,We utilize the generation of large atomic co...,"[{'version': 'v1', 'created': 'Thu, 8 Apr 1999...",2019-08-17,"[['Sautenkov', 'V. A.', ''], ['Lukin', 'M. D.'...",Physics
170614,solv-int/9511005,Wen-Xiu Ma,"Wen-Xiu Ma, Benno Fuchssteiner",Explicit and Exact Solutions to a Kolmogorov-P...,"14pages, Latex, to appear in Intern. J. Nonlin...",NaN,10.1016/0020-7462(95)00064-X,NaN,solv-int nlin.SI,NaN,Some explicit traveling wave solutions to a ...,"[{'version': 'v1', 'created': 'Tue, 14 Nov 199...",2019-08-15,"[['Ma', 'Wen-Xiu', ''], ['Fuchssteiner', 'Benn...",Not Exit
170615,solv-int/9809008,Victor Enolskii,"J C Eilbeck, V Z Enol'skii, V B Kuznetsov, D V...",Linear r-Matrix Algebra for a Hierarchy of One...,"plain LaTeX, 28 pages",NaN,NaN,NaN,solv-int nlin.SI,NaN,We consider a hierarchy of many-particle sys...,"[{'version': 'v1', 'created': 'Wed, 2 Sep 1998...",2019-08-17,"[['Eilbeck', 'J C', ''], [""Enol'skii"", 'V Z', ...",Not Exit
170616,solv-int/9909010,Pierre van Moerbeke,"M. Adler, T. Shiota and P. van Moerbeke",Pfaff tau-functions,42 pages,NaN,NaN,NaN,solv-int adap-org hep-th nlin.AO nlin.SI,NaN,Consider the evolution $$ \frac{\pl m_\iy}{\...,"[{'version': 'v1', 'created': 'Wed, 15 Sep 199...",2019-08-17,"[['Adler', 'M.', ''], ['Shiota', 'T.', ''], ['...",Not Exit
170617,solv-int/9909014,David Fairlie,D.B. Fairlie and A.N. Leznov,The General Solution of the Complex Monge-Amp\...,"13 pages, latex, no figures",NaN,10.1088/0305-4470/33/25/307,NaN,solv-int nlin.SI,NaN,A general solution to the Complex Monge-Amp\...,"[{'version': 'v1', 'created': 'Thu, 16 Sep 199...",2019-08-21,"[['Fairlie', 'D. B.', ''], ['Leznov', 'A. N.',...",Not Exit

# 1. 论文摘要和论文标题出现关键词的频率

In [19]:
taget1_df = df[['id', 'title', 'abstract']]
taget1_df

,id,title,abstract
0,0704.0297,Remnant evolution after a carbon-oxygen white ...,We systematically explore the evolution of t...
1,0704.0342,Cofibrations in the Category of Frolicher Spac...,Cofibrations are defined in the category of ...
2,0704.0360,Torsional oscillations of longitudinally inhom...,We explore the effect of an inhomogeneous ma...
3,0704.0525,On the Energy-Momentum Problem in Static Einst...,This paper has been removed by arXiv adminis...
4,0704.0535,The Formation of Globular Cluster Systems in M...,The most massive elliptical galaxies show a ...
...,...,...,...
170613,quant-ph/9904032,Enhancement of Magneto-Optic Effects via Large...,We utilize the generation of large atomic co...
170614,solv-int/9511005,Explicit and Exact Solutions to a Kolmogorov-P...,Some explicit traveling wave solutions to a ...
170615,solv-int/9809008,Linear r-Matrix Algebra for a Hierarchy of One...,We consider a hierarchy of many-particle sys...
170616,solv-int/9909010,Pfaff tau-functions,Consider the evolution $$ \frac{\pl m_\iy}{\...
170617,solv-int/9909014,The General Solution of the Complex Monge-Amp\...,A general solution to the Complex Monge-Amp\...

In [20]:
# 定义统计函数
def word_count(txt):
    word_dic = {}
    for ch in '''!"$%&()*+,-./;:<=>?@[\\]^_{|}~''\n\t ''':
        txt = txt.replace(ch, ' ')
    for word in txt.split(' '):
        word = word.lower()
        if word_dic.get(word):
            word_dic[word] += 1
        else:
            word_dic[word] = 1
    return word_dic


# 使用停词库过滤掉部分无用词
def wordsfilter(word_dic):
    stopwords = []
    # 读取停词库
    with open('../source/stopwords.txt') as f:
        for word in f:
            stopwords.append(word.split('\n')[0])
    for word in list(word_dic.keys()):  # 不能在遍历字典的同时修改字典, 所以转换成 list
        if word in stopwords:
            del word_dic[word]
    # 字典可以使用空字符串来作为 key 所以需要特殊处理一下
    del word_dic['']


# worldcloud 库 实现词云图
def creat_wordcloudImg(word_dic, file_name, word_num=50):
    import wordcloud
    img = wordcloud.WordCloud(background_color='white', font_path='msyh.ttc', width=2000, height=1500,
                              max_words=word_num).generate_from_frequencies(word_dic)
    img.to_file(f'../output/img/{file_name}.png')


def word_count2df(column):
    word_dic = {}
    for i in range(len(taget1_df)):
        for word in word_count(taget1_df[column][i]):
            if word_dic.get(word):
                word_dic[word] += 1
            else:
                word_dic[word] = 1
    wordsfilter(word_dic)
    # 排序
    # print(sorted(word_dic.items(), key=lambda x: x[1], reverse=True))
    # 创建词云图
    creat_wordcloudImg(word_dic, column, word_num=200)

    words_data = {'word': [], 'amount': []}
    for t in word_dic:
        words_data['word'].append(t)
        words_data['amount'].append(word_dic[t])
    return pd.DataFrame(words_data).sort_values(by='amount', ascending=False)


titleword_df = word_count2df('title')
titleword_df

                  word  amount
1620          learning    8862
88               based    7380
85             quantum    6757
247              model    6619
604           networks    5575
...                ...     ...
32552  autoassociative       1
32551             v354       1
32549   nanotopography       1
32547        versioned       1
54489            pfaff       1

[54490 rows x 2 columns]

In [21]:
abstract_df = word_count2df('abstract')
abstract_df

              word  amount
183          paper   45687
50           model   42507
26           based   42238
369           data   35753
329          study   33479
...            ...     ...
94059          drv       1
94058   supergates       1
94056   storydroid       1
94054     clubmark       1
162399        rary       1

[162400 rows x 2 columns]

# 2. 论文是否更新

In [22]:
taget2_df = df[['id', 'versions']]
taget2_df

                      id                                           versions
0              0704.0297  [{'version': 'v1', 'created': 'Tue, 3 Apr 2007...
1              0704.0342  [{'version': 'v1', 'created': 'Tue, 3 Apr 2007...
2              0704.0360  [{'version': 'v1', 'created': 'Tue, 3 Apr 2007...
3              0704.0525  [{'version': 'v1', 'created': 'Wed, 4 Apr 2007...
4              0704.0535  [{'version': 'v1', 'created': 'Wed, 4 Apr 2007...
...                  ...                                                ...
170613  quant-ph/9904032  [{'version': 'v1', 'created': 'Thu, 8 Apr 1999...
170614  solv-int/9511005  [{'version': 'v1', 'created': 'Tue, 14 Nov 199...
170615  solv-int/9809008  [{'version': 'v1', 'created': 'Wed, 2 Sep 1998...
170616  solv-int/9909010  [{'version': 'v1', 'created': 'Wed, 15 Sep 199...
170617  solv-int/9909014  [{'version': 'v1', 'created': 'Thu, 16 Sep 199...

[170618 rows x 2 columns]

In [23]:
import matplotlib.pyplot as plt

version_dic = {'id': [], 'version_num': []}
for i in range(len(taget2_df)):
    version_dic['id'].append(taget2_df['id'][i])
    version_dic['version_num'].append(str(len(list(taget2_df['versions'][i]))))
version_df = pd.DataFrame(version_dic)
version_dic = version_df.groupby('version_num').size().to_dict()
version_dic
# color = plt.get_cmap('Set3')(range(len(version_dic)))
#
# plt.pie(version_dic.values(), labels=version_dic.keys(), autopct='%0.1f%%', colors=color)
# plt.show()

{'1009': 1,
 '1010': 2,
 '1073': 1,
 '1075': 1,
 '1135': 1,
 '1137': 1,
 '1196': 1,
 '1201': 1,
 '1204': 1,
 '124': 4266,
 '125': 18541,
 '1259': 1,
 '126': 23483,
 '1266': 1,
 '1329': 1,
 '1330': 1,
 '1392': 1,
 '1522': 1,
 '1708': 1,
 '1714': 1,
 '186': 452,
 '187': 2922,
 '188': 6600,
 '189': 5693,
 '2153': 1,
 '2351': 1,
 '248': 42,
 '249': 360,
 '250': 1230,
 '251': 2017,
 '252': 1273,
 '310': 1,
 '311': 70,
 '312': 187,
 '313': 497,
 '314': 558,
 '315': 343,
 '3621': 1,
 '373': 10,
 '374': 28,
 '375': 116,
 '376': 206,
 '377': 170,
 '378': 81,
 '4072': 1,
 '435': 1,
 '436': 5,
 '437': 22,
 '438': 55,
 '439': 99,
 '440': 59,
 '441': 18,
 '497': 1,
 '498': 1,
 '499': 5,
 '500': 13,
 '501': 29,
 '502': 34,
 '503': 25,
 '504': 5,
 '5083': 1,
 '562': 6,
 '563': 10,
 '564': 11,
 '565': 14,
 '566': 6,
 '62': 29260,
 '626': 6,
 '627': 7,
 '628': 5,
 '629': 7,
 '63': 71683,
 '630': 3,
 '687': 2,
 '688': 1,
 '690': 4,
 '691': 2,
 '692': 8,
 '693': 1,
 '694': 3,
 '752': 2,
 '753': 1,
 '754': 4,
 '755': 5,
 '756': 4,
 '757': 2,
 '758': 1,
 '817': 1,
 '818': 2,
 '819': 2,
 '820': 1,
 '821': 1,
 '822': 1,
 '879': 1,
 '880': 1,
 '881': 1,
 '883': 2,
 '884': 2,
 '942': 1,
 '946': 1,
 '947': 1,
 '948': 1}

# 3.论文在 arxiv 系统中所属的类别统计

In [24]:
categorie_num = df.groupby('group').size().rename('num')
categorie_num

group
Computer Science                              43737
Economics                                       557
Electrical Engineering and Systems Science     4687
Mathematics                                   41478
Not Exit                                         47
Physics                                       72337
Quantitative Biology                           2040
Quantitative Finance                            883
Statistics                                     4852
Name: num, dtype: int64